config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  devise_for :users
  resources :users
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :event
    belongs_to :user
    
    validates :stripe_customer_id, presence: true
    
    
end

app/models/event.rb
class Event < ApplicationRecord
    
    has_many :attendances
    has_many :users, through: :attendances
    belongs_to :user
    
    validates :start_date, presence: true
    validates :duration, presence: true
    validates :title, presence: true, length:{minimum:10}
    validates :description, presence: true, length:{minimum: 100}
    validates :price, presence: true
    validates :location, presence: true
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    has_many :attendances
    has_many :events
    
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    PASSWORD_FORMAT = /\A
        (?=.{8,})          # Must contain 8 or more characters
        (?=.*\d)           # Must contain a digit
        (?=.*[a-z])        # Must contain a lower case character
        (?=.*[A-Z])        # Must contain an upper case character
    /x
    #(?=.*[[:^alnum:]]) # Must contain a symbol
    
    #validates :first_name,presence: true
    #validates :last_name,presence: true
    validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
    validates :encrypted_password, presence: true, format: { with: PASSWORD_FORMAT }
    #validates :description, presence: true

    after_create :welcome_send
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :show]
  
    def new
    @event = Event.new
    end
  
    def create
      @event = Event.new(start_date: params[:start_date],
        duration: params[:duration],
        title: params[:title],
        description: params[:description],
        price: params[:price],
        location: params[:location],
        user: current_user)
  
      if @event.save
        flash[:success] = "Evènement ajouté !"
        redirect_to events_path #Affiche l'index des events
      else
        render 'new' # Reste sur la view de events New.
      end
    end
  
    def show
      # On stock dans une variable l'entrée de la BDD qui
      # correspond à notre event via le paramètre récupéré dans l'URL
      @event = Event.find(params[:id])
    end
  
    def index
      # On récupère tous les events dans une variable
      @all_events = Event.all
      puts "*"*60
      puts "Fetching database for events"
      # On vérifie que tout fonctionne sur le server avec des puts dans le terminal
      puts "-"*60    
      puts @all_events 
      puts "*"*60
    end
  
    def edit
      @event = Event.find(params[:id])
  
      # Si l'utilisateur n'est pas l'auteur on redirige vers la page event sans pouvoir l'éditer
      is_not_author? 
    end
  
    def update
      @event = Event.find(params[:id])
  
      # Si le user n'est pas l'auteur on redirige vers la page event sans pouvoir l'éditer, gràce à is_not_author?
      is_not_author?
  
      if @event.update(start_date: params[:start_date],
        duration: params[:duration],
        title: params[:title],
        description: params[:description],
        price: params[:price],
        location: params[:location])
  
        flash[:success] = "L'évènement a été modifié !"
        redirect_to event_path
      else
        render 'edit'
      end
    end
  
    def destroy
      @event = Event.find(params[:id])
      
      if !is_not_author? 
        @event.destroy
        flash[:alert] = "L'évènement a été effacé !"
        redirect_to events_path
      end
    end
  
    # méthode pour sécuriser l'édition et la suppression des gossips
    def is_not_author?
      if current_user != @event.user
        flash[:alert] = "Tu n'es pas l'auteur de cet évènement!"
        redirect_to event_path
      end
    end
end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
    @user = User.new
    end

    def create

        @user = User.new(email: params[:email],
        password: params[:password],
        password_confirmation: params[:password_confirmation]
        )

        if @user.save
            flash[:success] = "Bienvenue #{@user.first_name}!"
            log_in(@user)
            redirect_to root_path #Affiche l'index des gossips
        else
            render 'new' # Reste sur la view de gossips New.
        end   
    end

    def show
        @user = User.find(params[:id])
    end

    def index
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
    
        # Si le user n'est pas l'auteur on redirige vers la page du potin sans pouvoir l'éditer, gràce à is_not_author?
        is_not_author?
    
        if @user.update(first_name: params[:first_name],
          last_name: params[:last_name],
          description: params[:description])
    
          flash[:success] = "Les infos ont été modifié !"
          redirect_to user_path(@user)
        else
          render 'edit'
        end
      end

      def destroy
        @user = User.find(params[:id])
        
        if !is_not_author? 
          @user.destroy
          flash[:alert] = "Le compte a été effacé !"
          redirect_to root_path
        end
      end

    # méthode pour sécuriser l'édition et la suppression des users
    def is_not_author?
    if current_user != @user
      flash[:alert] = "Tu n'es pas propriétaire de ce compte !"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid text-center pt-6 pb-5">
	<div class="container">
		<div class="row">
			<div class="col-6 mx-auto">
				<h2>Qu'est ce qu'il se passe autour de chez toi ?</h2>

				<p>Voici une liste des évènements, tu peux aussi en ajouter un en cliquant sur le lien ci-dessous.</p>
				<hr class="my-4">	
				<p><%= link_to "Je crée mon évènement!", new_event_path, class: "btn btn-primary mb-0" %>
				</p>
			</div>
		</div>
	</div>
</div>

<!-- Un petit carroussel des familles pour montrer qqs fake events non cliquables -->
<div class="carouselContainer mt-3 mb-3 text-center">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			<li data-target="#carousel-example-generic" data-slide-to="3"></li>
			<li data-target="#carousel-example-generic" data-slide-to="4"></li>
			<li data-target="#carousel-example-generic" data-slide-to="5"></li>

		</ol>
	  	<!-- Wrapper for slides -->
	  		<div class="carousel-inner" role="listbox">
	    		<div class="carousel-item active">
	    			<%= image_tag ( "https://i.ytimg.com/vi/c3aCLfafpKY/maxresdefault.jpg"),style: 'height:550px;width:1100px;' %>
	    		</div>

	    		<div class="carousel-item">
	      			<%= image_tag ( "https://static.sportpaleisgroep.be/sportpaleis/img/events/2847/62ada91400cb075b16d48ac67cf7eb522f5e4f06/billboard.jpg"), style: 'height:550px;width:1100px;'%>
	    		</div>

	    		<div class="carousel-item">
	      			<%= image_tag ( "https://cdn.wegow.com/media/artists/adele/adele-1503056056.33.2560x1440.jpg"), style: 'height:550px;width:1100px;'%>
				</div>
				
				<div class="carousel-item">
	      			<%= image_tag ( "https://media.stubhubstatic.com/stubhub-catalog/d_defaultLogo.jpg/t_f-fs-0fv,q_auto:low,f_auto,c_fill,dpr_2.0,$w_750,$h_416/performer/488102/kmjwj4uiivtbtotecgp4"), style: 'height:550px;width:1100px;'%>
				</div>
				
				<div class="carousel-item">
	      			<%= image_tag ( "https://media2.ledevoir.com/images_galerie/nwd_777038_611870/image.jpg"), style: 'height:550px;width:1100px;'%>
				</div>
				
				<div class="carousel-item">
	      			<%= image_tag ( "https://cdn-media.rtl.fr/cache/ofofy8ztCVaOWy1wE0HTWw/880v587-0/online/image/2014/0611/7772540114_ray-charles.jpg"), style: 'height:550px;width:1100px;'%>
	    		</div>

	  		</div>
	  	<!-- Controls -->
	 		<a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
	  			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
	        	<span class="sr-only">Previous</span>
	    	</a>
	    	<a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
	        	<span class="carousel-control-next-icon" aria-hidden="true"></span>
	        	<span class="sr-only">Next</span>
	    	</a>
	</div>
</div>


<!-- Liste des events -->

	<div class="list-group col-6 mx-auto">
		<% @all_events.each do |event| %>

		<div class="row justify-content-center">
			<%= link_to event, class: "list-group-item list-group-item-action mb-0 col-9 mb-3" do %>
			<div class="row">
				<div class="col-9">
					<h5 class="mb-1"><%= event.title %></h5>
					<small><%= "de #{event.user.first_name} #{event.user.last_name}" %></small>
					<p><%= event.description %></p>
					<p>Quand ? <%= event.start_date %> </p>
					<p>Où ? <%= event.location %></p>
				</div>
				<div class="col-3 text-right">
					<p> <%= event.price %>€</p>
				</div>
			</div>
			<% end %>
		</div>
		<% end %>
	</div>

app/views/events/new.html.erb
<!-- On inclus le contenu dans un row et une colonne pour limiter la largeur -->
<div class="container">
	<div class="row">
		<div class="col-6 mx-auto">
			<!-- Le titre de la page -->
			<h3 class="card-title text-center m-4">Ajouter un nouvel évènement</h3>



			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'create'), method: "post" do %>

			<%= label_tag 'Titre' %>
			<%= text_field_tag 'title', @event.title, class: "form-control" %>
			<br /> <br />

			<%= label_tag 'Texte' %>
			<%= text_area_tag 'description', @event.description, class: "form-control"  %>
            <br /> <br />
            
            <%= label_tag 'Date' %>
			<%= text_field_tag 'start_date', @event.start_date, class: "form-control" %>
            <br /> <br />

            <%= label_tag 'Durée' %>
			<%= text_field_tag 'duration', @event.duration, class: "form-control" %>
            <br /> <br />
            
            <%= label_tag 'Lieu' %>
			<%= text_field_tag 'location', @event.location, class: "form-control" %>
            <br /> <br />
            
            <%= label_tag 'Prix' %>
			<%= text_field_tag 'price', @event.price, class: "form-control" %>
			<br /> <br />

			<%= submit_tag "Ajouter l'évènement", class: "btn btn-primary" %>

			<% end %>

			<!-- Pour afficher les erreurs possibles -->
			<% if @event.errors.any? %>

			<div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
				<p><strong>We couldn't create the event for the following reason(s) :</strong></p>
				<ul>
					<% @event.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<% end %>
				</ul>
			</div>

			<% end %>

		</div>
	</div>
</div>

app/views/events/show.html.erb
<!-- contenu dans un row et une colonne pour limiter la largeur -->
<div class="container">
	<div class="row">
		<div class="col-6 mx-auto">

			<!-- Titre event -->
			<h2 class="card-title text-center m-4">	<%= @event.title %> </h2>

			<div class="row justify-content-md-center mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body text-center">

							<!-- contenu event -->

							<p class="card-title lead">	<%= @event.description %></p>

							<!-- date de création event -->

							<small class="card-text text-muted"><%= @event.created_at %></small>

							<!-- auteur event -->

							<!-- On affiche l'auteur sous forme de lien pour pouvoir accéder à sa page.
							Le lien permet d'accéder à la page auteur avec son ID en paramètre dans
							l'URL -->
							<p class="card-text text-muted">
							Auteur : <%= link_to "#{@event.user.first_name} #{@event.user.last_name}", user_path(@event.user) %>
							</p>

							<!-- si la personne connectée a écrit l'event elle a accès aux options d'edit -->

							<% if @event.user == current_user %>
								<%= link_to "Modifier l'event", edit_event_path(@event), class: "btn btn-primary" %> <%= link_to "Effacer le potin", event_path(@event), data: {confirm: "Etes-vous sûr-e?"}, method: "delete", class: "btn btn-danger mb-0 ml-2" %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- favicon THP -->
    <link rel="apple-touch-icon" sizes="180x180" href="https://www.thehackingproject.org/assets/favicon/apple-touch-icon-c01aaccf467f7cc3d79bbce743d60779f5b833fdc4500cebd07a5e11a07a5c31.png">
    <link rel="icon" type="image/png" sizes="32x32" href="https://www.thehackingproject.org/assets/favicon/favicon-32x32-804b12d1c41c60fe721477b7c3b0a32811dc610580dd40ac92f1cc04cbd05ca4.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://www.thehackingproject.org/assets/favicon/favicon-16x16-d96ba65e5785d32474df9ebc6fbfd5442c751d527b10981a474bc3b7a4079d01.png">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Eventbrite", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- On affiche le menu avec des classes Bootstrap-->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <!-- Les liens link_to pour ne pas écrire d'URL en dur -->
        <%= link_to "Accueil", root_path, class: "nav-item nav-link" %>
        <%= link_to "Créer un évènement", new_event_path, class: "nav-item nav-link" %>
        <%= link_to "Contact", '#', class: "nav-item nav-link" %>

        <% if user_signed_in? %>
          <!-- Dropdown pour se déco et profil --> 
          <ul class="navbar-nav">  
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Utilisateur</a>
              <div class="dropdown-menu" aria-labelledby="dropdown08">
                <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item"%>  
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item"%>  
              </div>
            </li>
          </ul>  
        

        <% else %>
        <!-- Dropdown pour incription et login --> 
        <ul class="navbar-nav">  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown08" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Utilisateur</a>
            <div class="dropdown-menu" aria-labelledby="dropdown08">
              <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item"%>  
              <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item"%>  
            </div>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
    </nav>
  
    <%= yield %>

    <footer class="page-footer mt-4 bg-dark">
      <div class="container text-center text-light">
        Cette version d'Eventbrite vous est proposée par Maxime Pierron de Grenoble.
      </div>
    </footer>

    <!-- On appelle le Javascript de Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>

app/views/users/edit.html.erb
<!-- On inclus le contenu dans un row et une colonne pour limiter la largeur -->
<div class="container">
	<div class="row">
		<div class="col-6 mx-auto">
			<!-- Le titre de la page -->
			<h3 class="card-title text-center m-4">Modifier mes infos</h3>

			<!-- Zone du formulaire -->
			<%= form_tag url_for(action: 'update'), method: "patch" do %>
			
			<%= label_tag 'Prénom' %>
			<%= text_field_tag 'first_name',  @user.first_name, class: "form-control" %>
            <br/>
            
            <%= label_tag 'Nom de famille' %>
			<%= text_field_tag 'last_name',  @user.last_name, class: "form-control" %>
            <br/>

			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', @user.description, class: "form-control" %>
			<br/>

			<%= submit_tag "Confirmer", class: "btn btn-primary" %>

			<% end %>

			<!-- Pour afficher les erreurs possibles -->
			<% if @user.errors.any? %>

			<div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
				<p><strong>We couldn't edit the user infos for the following reason(s)</strong></p>
				<ul>
					<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<% end %>
				</ul>
			</div>

			<% end %>

		</div>
	</div>
</div>

app/views/users/show.html.erb
<!-- On inclus le contenu dans un row et une colonne pour limiter la largeur -->
<div class="row">
    <div class="col-6 mx-auto">

        <h3 class="card-title text-center m-4" ><%= "#{@user.first_name} #{@user.last_name}" %></h3>

        <!-- Sa description -->
        <p class="text-center"><em><%= @user.description %></em></p>

        <ul class="list-group-flush">
            <!-- Son email -->
            <li class="list-group-item"><%= "Email : #{@user.email}" %></li>
            <!-- La date de son inscription -->
            <li class="list-group-item"><%= "Inscris le : #{@user.created_at}" %></li>
            <% if current_user.id == @user.id %>
                <%= link_to 'Modifier mes infos', edit_user_path(@user) %> |
                <%= link_to "Modifier mon mot de passe", edit_user_registration_path(@user) %> |
                <%= link_to "Supprimer le compte", user_path, data: {confirm: "Etes-vous sûr-e?"}, method: "delete", class: "btn btn-danger mb-0 ml-2" %>
            <% end %>
        </ul>

        


    </div>
</div>